### ISSUE TITLE
1.13 Errors

### ISSUE THREAD

**Issue by mercurialmusic** [dumptruckman/ChestRestock#23]
You may be working on this already, but just in case it's useful, this is the error I'm getting on a 1.13 test server: https://pastebin.com/Umcmezqu

The plugin seems to load without issue, but creating a chest results in "An internal error occurred". However, it still seems to register the chest since I'm able to directly start setting options (set period, etc.). But then items disappear from the chest when opening for the first time after creation and /cr restock has no effect. No other errors are printed in console and items don't appear to be "ghost" items -- breaking the chest doesn't drop anything and clicking on the spaces where items were is just clicking on air. Really love this plugin and hope it lives on! Thanks!

**Comment by Blueeyestar** [comment]
pity the plugin is probably abandoned .... there is no comparable plugin ... really a pity

**Comment by mercurialmusic** [comment]
Nah, he's still around. Same thing happened in 1.12 -- just took a while to get to it, and I'm happy to be patient. You're right that there does not seem to be an alternative, though.

**Comment by Blueeyestar** [comment]
Do you already know when the update comes out?

**Comment by Fabrimat** [comment]
I have updated the plugin to 1.13.x but it's still unstable. 
Check it [here](https://github.com/Fabrimat/ChestRestock/releases/tag/2.5.0).

**Comment by Blueeyestar** [comment]
Thank you for updating it. This plugin is really great for every server

**Comment by Blueeyestar** [comment]
Unfortunately, the box remains empty if the owner has looted once as the users although I have the perm: **chestrestock.bypass.lootlimit. ***

**Comment by XxDILBERTxX** [comment]
Paste has expired here is my error for 1.13.2:
`[17:46:20] [Server thread/INFO]: XxDILBERTxX issued server command: /cr create
[17:46:20] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cr' in plugin ChestRestock v2.3.2-b106
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-40cbae4]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-40cbae4]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-40cbae4]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1636) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-40cbae4]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1476) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-40cbae4]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-40cbae4]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-40cbae4]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-40cbae4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-3cb9dcb-40cbae4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.2.jar:git-Spigot-3cb9dcb-40cbae4]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-3cb9dcb-40cbae4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-3cb9dcb-40cbae4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-3cb9dcb-40cbae4]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.ItemStack.<init>(I)V
	at com.dumptruckman.chestrestock.util.InventoryTools.fillWithAir(InventoryTools.java:16) ~[?:?]
	at com.dumptruckman.chestrestock.DefaultCRChest.update(DefaultCRChest.java:110) ~[?:?]
	at com.dumptruckman.chestrestock.DefaultChestManager.createChest(DefaultChestManager.java:205) ~[?:?]
	at com.dumptruckman.chestrestock.command.CreateCommand.runCommand(CreateCommand.java:33) ~[?:?]
	at com.dumptruckman.chestrestock.command.TargetedChestRestockCommand.runCommand(TargetedChestRestockCommand.java:36) ~[?:?]
	at com.dumptruckman.chestrestock.pluginbase.util.commandhandler.CommandHandler.checkAndRunCommand(CommandHandler.java:234) ~[?:?]
	at com.dumptruckman.chestrestock.pluginbase.util.commandhandler.CommandHandler.processFoundCommands(CommandHandler.java:120) ~[?:?]
	at com.dumptruckman.chestrestock.pluginbase.util.commandhandler.CommandHandler.locateAndRunCommand(CommandHandler.java:70) ~[?:?]
	at com.dumptruckman.chestrestock.pluginbase.util.commandhandler.CommandHandler.locateAndRunCommand(CommandHandler.java:48) ~[?:?]
	at com.dumptruckman.chestrestock.pluginbase.plugin.AbstractBukkitPlugin.onCommand(AbstractBukkitPlugin.java:141) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-40cbae4]
	... 15 more`
